name release
on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'
jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go 1.16
        uses: actions/setup-go@v1
        with:
          go-version: 1.16
        id: go

      - name: Check out code into the Go module directory
        uses: actions/checkout@v1

      - name: Build and pack neargo for Linux
        run: |
          GOOS=linux GOARCH=amd64 make
          cd .target
          tar -czf neargo-linux-amd64.tar.gz neargo
          cd ..
      - name: Build and pack neargo for Linux ARMv7
        run: |
          GOOS=linux GOARCH=arm GOARM=7 make
          cd .target
          tar -czf neargo-linux-armv7.tar.gz neargo+
          cd ..
      - name: Build and pack neargo for Linux ARM64
        run: |
          GOOS=linux GOARCH=arm64 make
          cd .target
          tar -czf neargo-linux-arm64.tar.gz neargo
          cd ..
      - name: Build and pack neargo for macOS
        run: |
          GOOS=darwin GOARCH=amd64 make
          cd .target
          tar -czf neargo-macos-amd64.tar.gz neargo
          cd ..
      - name: Build and pack neargo for Windows
        run: |
          GOOS=windows GOARCH=amd64 make
          cd .target
          zip neargo-windows-amd64.zip neargo.exe
          cd ..

      - uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "latest"
          prerelease: true
          title: "Development Build"
          files: |
            .target/neargo-linux-amd64.tar.gz
            .target/neargo-linux-armv7.tar.gz
            .target/neargo-linux-arm64.tar.gz
            .target/neargo-macos-amd64.tar.gz
            .target/neargo-windows-amd64.zip